#!/bin/bash
#####################
# like MacOSX "open" command (like the old konqueror or even better )))
# if the argument is a folder or there is no arguments - open a filemanager (e.g. dolphin)
# if it's a file - open it with e.g. okular (default)
# open text files with e.g. vi etc.
#####################
#***********************
#file types (like in file-output), one can use "or"(|) (write "'--'" if not defined):
ftype="PostScript video GIMP image audio '--' RAR archiv '--' Office|OpenDocument HTML PDF text"
#file extension (write "'--'" if not defined)
exten=("ps" "avi|mkv|wmv|mpg|mp4" "xcf" "gif|png|jpg" "mp3" "qti" "rar" "zip|7z" "xoj" "ppt|odg|oxt" "html" "pdf" "txt")
#file opener (sorted according to ftype) 
if command -v explorer.exe &> /dev/null; then 
  # WSL
  opener=(sumatra vlc gimp i_view32 amarok qtiplot "7z x" "7z x" xournal explorer.exe explorer.exe sumatra vim)
  # default opener 
  openfolder="explorer.exe"
  openfile="explorer.exe"
else 
  # Linux
  opener=(okular vlc gimp gwenview amarok qtiplot "unrar x" ark xournal ooffice opera okular vi)
  # default opener 
  openfolder="dolphin"
  openfile="okular"
fi
opentext="vim"
#***********************
# some commands
FILE="file"
GREP="grep -E"
#***********************
if [ $# -gt 0 ]; then
  for i in "$@"; do
    name=$i
    echo $name
    if [ -f "$name" ]; then
      filetyp=$($FILE "$name")
      filetyp=${filetyp/"$name:"}
      echo $filetyp
      let j=0
      next=''
      for types in $ftype; do
        ft=$(echo "$filetyp" | $GREP -i $types)
        ext=$(echo "$name" | $GREP -i "\.(${exten[$j]})\$") 
        if [[ -n "$ft" || -n "$ext" ]]; then
          ${opener[$j]} "$name"
          next='1'
          break
        fi
        let j=$j+1
      done
      if [ -n "$next" ]; then
        continue
      fi
      $openfile "$name"
    elif [ -d "$name" ]; then
      $openfolder "$name"
    else
      $opentext "$name"
    fi
  done
else
  $openfolder .
fi
